#pragma once
#include "event/EventUtils.hpp"


namespace event
{
    /**
     * @brief Forward declaration of the EventSystem template class
     * @tparam K The key type used to identify events
     */
    template<typename K /* key */> class EventSystem;
}


namespace ecs
{
    // Forward declarations
    class Registry;


    /**
     * @brief Type used as key for event identification in the ECS
     *
     * Events are identified by unique keys derived from their types.
     * Using std::size_t provides efficient hashing and lookup in containers.
     */
    using eventKey_t = std::size_t;

    /**
     * @brief Generates a unique compile-time key for an event type
     *
     * @tparam Event The event type to generate a key for
     * @return constexpr std::size_t A unique hash code for the event type
     *
     * @note Uses typeid(Event).hash_code() which is constexpr-friendly
     *       and provides a unique identifier per type at compile time
     *
     * @par Example:
     * @code
     * struct PlayerDiedEvent {};
     * auto key = TryGetKey<PlayerDiedEvent>(); // Unique identifier
     * @endcode
     */
    template<class Event>
    constexpr std::size_t TryGetKey()
    {
        return typeid(Event).hash_code();
    }

    /**
     * @brief ECS-specific event system type alias
     *
     * Specializes the generic EventSystem to use eventKey_t (std::size_t)
     * as the key type for event identification within the ECS.
     */
    using EventSystem = event::EventSystem<eventKey_t>;


    /**
     * @brief Structure containing initialization parameters for system startup.
     *
     * Provides a flexible container for passing configuration data to systems
     * during their initialization phase. The structure uses a void pointer for
     * arguments to support any configuration type, making it extensible without
     * modifying the base interface.
     */
    struct InitState
    {
        const char* nameFactory;            ///< Identifier for the systemsManager or creator of this system
        void* args;                         ///< Pointer to system-specific initialization arguments
    };

    /**
     * @brief Initialization state for system event subscription.
     *
     * Contains required context for subscribing a system to the ECS event system,
     * including a reference to the event dispatcher and optional priority for
     * ordering event processing.
     */
    struct SubscribeState
    {
        std::reference_wrapper<EventSystem> eventSystem;       ///< Reference to the ECS event system used for subscriptions
        event::priority_t priority = event::DEFAULT_PRIORITY;  ///< Priority of the system in event processing order (higher = earlier execution)
    };

    /**
     * @brief Structure containing context information for system updates.
     *
     * Passed to systems during each update cycle, providing contextual information
     * about the current update phase. Currently contains the update tag, which
     * allows systems to know which phase they're being executed in and potentially
     * adjust their behavior accordingly.
     */
    struct UpdateState
    {

    };

    /**
     * @typedef systemHash_t
     * @brief Type alias for system identifier hash.
     *
     * Represents a unique identifier for a system, typically generated by
     * hashing the system's type name or using a compile-time hash function.
     */
    using systemHash_t = std::size_t;

    /**
    * @brief Generates a unique compile-time hash for a system type.
    *
    * Creates a hash value that uniquely identifies the system class type.
    * Used for system lookup, dependency tracking, and registration.
    *
    * @tparam SystemCls The system class type to generate a hash for
    * @return constexpr systemHash_t A unique hash code for the system type
    *
    * @note Uses typeid(SystemCls).hash_code() which is constexpr-friendly
    *       and provides a unique identifier per type at compile time
    *
    * @par Example:
    * @code
    * class MovementSystem {};
    * auto hash = getSystemHash<MovementSystem>(); // Unique system identifier
    * @endcode
    */
    template<class SystemCls>
    constexpr systemHash_t getSystemHash()
    {
        return typeid(SystemCls).hash_code();
    }

    /**
     * @brief Defines dependencies between systems.
     *
     * Specifies a set of systems that must be executed before or after
     * a given system, ensuring proper execution order and data dependencies.
     * Used by the system scheduler to resolve execution order.
     *
     * @note This structure holds a pointer to an array of system hashes,
     *       allowing static initialization at compile time for performance.
     */
    struct DependentSystems
    {
        const systemHash_t* systemHashes = nullptr;
        std::size_t count = 0;
    };

}
